name: Trigger training job on merge of pull request to main

on:
  push:
    branches:
      - main

jobs:
  trainreg:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="rg-dev-mlops"
        az configure --defaults workspace="mlw-dev-mlops"
    - name: Train and register a classification model on diabetes data in compute cluster
      run: |
        cd src
        az ml job create --file job.yml

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: trainreg
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="rg-dev-mlops"
        az configure --defaults workspace="mlw-dev-mlops"
    - name: List registered models
      run: |
        az ml model list

